import type { Section } from '../../stores/gameStore'
import { useState } from 'react'
import { taxiModels } from '../../data/taxis'
import { postVehicleModels } from '../../data/postVehicles'
import { cities, countries, getCity } from '../../data/cities'
import { transportModels } from '../../data/transport'
import type { AutomationPolicy, Branch, BusinessContract, City, CoachRoute, Company, CompanyGoal, DepotFacility, Driver, DriverCandidate, ExteriorAccessory, Loan, RefuelStrategy, ResearchId, Specialization, TaxiJob, Tour, TransportAsset, TransportMode, TransportRoute, TravelAgency, Vehicle, VehicleUpgrade } from '../../models/game'
import { driverTraitDetails, upgradeDetails } from '../../services/earlyGameEngine'
import { maintenanceCost, nextServiceAtKm, replacementRecommendation, vehicleAgeYears, vehicleMarketValue, warrantyActive } from '../../services/vehicleEconomics'
import { canResearch, hasResearch, researchDisciplines, researchNodes, researchPoints } from '../../services/research'
import { DEPOT_FACILITY_MAX_LEVEL, depotFacilityDetails, depotFacilityLevel, depotFacilityUpgradeCost, fleetSlotCapacity, garageUpgradeCost, LEASING_UNLOCK_LEVEL, maxJobDistanceForFleet } from '../../services/companyProgression'

interface SectionSheetProps { section: Exclude<Section, 'map' | 'jobs' | 'hotels'>; company: Company; activeCityId: string; branches: Branch[]; customCities: City[]; agencies: TravelAgency[]; tours: Tour[]; coachRoutes: CoachRoute[]; countryLicenses: string[]; transportAssets: TransportAsset[]; transportRoutes: TransportRoute[]; contracts: BusinessContract[]; specialization: Specialization | null; completedResearch: ResearchId[]; automation: AutomationPolicy; vehicles: Vehicle[]; garageLevel: number; drivers: Driver[]; driverCandidates: DriverCandidate[]; goals: CompanyGoal[]; jobs: TaxiJob[]; loans: Loan[]; cash: number; onClose: () => void; onReset: () => void; onBuyTaxi: (modelId: string) => void; onLeaseTaxi: (modelId: string) => void; onUpgradeGarage: () => void; onBuyPostVehicle: (modelId: string) => void; onStartPostalRoute: (vehicleId: string) => void; onBuyRentalCar: (modelId: string) => void; onStartRental: (vehicleId: string) => void; onBuyCountryLicense: (countryCode: string) => void; onBuildStation: () => void; onSwitchStation: (cityId: string) => void; onUnlockResearch: (researchId: ResearchId) => void; onUpgradeDepotFacility: (cityId: string, facility: DepotFacility) => void; onOpenAgency: () => void; onCreateTour: () => void; onDispatchTour: (tourId: string, vehicleId: string) => void; onBuyTourBus: () => void; onBuyCoach: () => void; onCreateCoachRoute: (toCityId: string) => void; onDispatchCoach: (routeId: string, vehicleId: string) => void; onBuyTransportAsset: (mode: TransportMode) => void; onCreateTransportRoute: (mode: TransportMode, toCityId: string) => void; onDispatchTransport: (routeId: string, assetId: string) => void; onSetAutomation: (patch: Partial<AutomationPolicy>) => void; onAcceptContract: (contractId: string) => void; onChooseSpecialization: (specialization: Specialization) => void; onTakeLoan: (amount: number) => void; onSellVehicle: (vehicleId: string) => void; onSetDriverShift: (driverId: string, shift: Driver['shift']) => void; onHireDriver: (candidateId: string, vehicleId: string) => void; onRefreshCandidates: () => void; onServiceVehicle: (vehicleId: string, service: 'quick' | 'full' | 'preventative') => void; onInstallUpgrade: (vehicleId: string, upgrade: VehicleUpgrade) => void; onSetRefuelStrategy: (vehicleId: string, strategy: RefuelStrategy) => void; onRefuelVehicle: (vehicleId: string) => void; onClaimGoal: (goalId: string) => void; onToggleAccessory: (vehicleId: string, accessory: ExteriorAccessory) => void }
const money = new Intl.NumberFormat('en-IE', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 })
const exteriorAccessories: Array<{ id: ExteriorAccessory; label: string; icon: string }> = [
  { id: 'panoramic-roof', label: 'Panoramic roof', icon: '🌅' }, { id: 'towbar', label: 'Towbar', icon: '🪝' },
  { id: 'roof-rack', label: 'Roof rack', icon: '🧳' }, { id: 'mud-flaps', label: 'Mud flaps', icon: '💦' },
  { id: 'wind-deflectors', label: 'Wind deflectors', icon: '🌬️' },
]
const getModel = (vehicle: Vehicle) => taxiModels.find((model) => model.id === vehicle.modelId || (!vehicle.modelId && model.powertrain === vehicle.powertrain))

function VehicleLifecycle({ vehicle }: { vehicle: Vehicle }) {
  const marketValue = vehicleMarketValue(vehicle)
  const netReturn = (vehicle.lifetimeRevenue ?? 0) - (vehicle.lifetimeExpenses ?? 0) - (vehicle.purchasePrice ?? vehicle.value) + marketValue
  const serviceRemaining = nextServiceAtKm(vehicle) - (vehicle.odometerKm ?? 0)
  return <div className="lifecycle-card">
    <div className="lifecycle-heading"><span><small>VEHICLE LIFECYCLE</small><b>{replacementRecommendation(vehicle)}</b></span><strong>{money.format(marketValue)}<small>market value</small></strong></div>
    <div className="lifecycle-grid">
      <span><small>ODOMETER</small><b>{Math.round(vehicle.odometerKm ?? 0).toLocaleString()} km</b></span>
      <span><small>AGE</small><b>{vehicleAgeYears(vehicle).toFixed(1)} years</b></span>
      <span><small>LIFETIME REVENUE</small><b>{money.format(vehicle.lifetimeRevenue ?? 0)}</b></span>
      <span><small>NET RETURN</small><b className={netReturn >= 0 ? 'positive' : 'negative'}>{money.format(netReturn)}</b></span>
    </div>
    <div className="lifecycle-status"><span>{warrantyActive(vehicle) ? '✓ Warranty active' : 'Warranty expired'}</span><span className={serviceRemaining <= 0 ? 'due' : ''}>{serviceRemaining <= 0 ? `Service overdue by ${Math.abs(Math.round(serviceRemaining)).toLocaleString()} km` : `Major service in ${Math.round(serviceRemaining).toLocaleString()} km`}</span>{vehicle.powertrain === 'electric' && <span>Battery {Math.round(vehicle.batteryHealth ?? 100)}%</span>}</div>
  </div>
}


function ResearchTree({ company, completed, onUnlock }: { company: Company; completed: ResearchId[]; onUnlock: (id: ResearchId) => void }) {
  const points = researchPoints(company.level, completed)
  return <div className="research-lab">
    <header className="research-hero"><span className="research-orbit">✦</span><div><small>INNOVATION POINTS</small><strong>{points}</strong><p>Earn one point every company level. Research is permanent and benefits your entire empire.</p></div><b>{completed.length}<small> technologies</small></b></header>
    <div className="research-progress"><span style={{ width: `${completed.length / researchNodes.length * 100}%` }} /></div>
    {(Object.keys(researchDisciplines) as Array<keyof typeof researchDisciplines>).map((discipline) => {
      const details = researchDisciplines[discipline]
      const nodes = researchNodes.filter((node) => node.discipline === discipline)
      return <section className="research-discipline" style={{ '--tech-color': details.color } as Record<string, string>} key={discipline}>
        <header><i>{details.icon}</i><div><strong>{details.name}</strong><small>{nodes.filter((node) => completed.includes(node.id)).length} / {nodes.length} researched</small></div></header>
        <div className="research-path">{nodes.map((node, index) => {
          const done = completed.includes(node.id)
          const prerequisitesMet = node.requires.every((id) => completed.includes(id))
          const available = canResearch(node, completed, company.level)
          return <div className={`research-node ${done ? 'researched' : available ? 'available' : 'locked'}`} key={node.id}>
            {index > 0 && <span className={`research-link ${prerequisitesMet ? 'connected' : ''}`} />}
            <button disabled={!available} onClick={() => onUnlock(node.id)} aria-label={`${done ? 'Researched' : 'Research'} ${node.name}`}>
              <span className="node-icon">{done ? '✓' : node.icon}</span><span className="node-copy"><small>TIER {node.tier}</small><strong>{node.name}</strong><em>{node.description}</em><b>{node.effect}</b></span><span className="node-cost">{done ? 'DONE' : prerequisitesMet ? `${node.cost} ✦` : 'LOCKED'}</span>
            </button>
          </div>
        })}</div>
      </section>
    })}
  </div>
}

export function SectionSheet({ section, company, activeCityId, branches, customCities, agencies, tours, coachRoutes, countryLicenses, transportAssets, transportRoutes, contracts, specialization, completedResearch, automation, vehicles, garageLevel, drivers, driverCandidates, goals, jobs, loans, cash, onClose, onReset, onBuyTaxi, onLeaseTaxi, onUpgradeGarage, onBuyPostVehicle, onStartPostalRoute, onBuyRentalCar, onStartRental, onBuyCountryLicense, onBuildStation, onSwitchStation, onUnlockResearch, onUpgradeDepotFacility, onOpenAgency, onCreateTour, onDispatchTour, onBuyTourBus, onBuyCoach, onCreateCoachRoute, onDispatchCoach, onBuyTransportAsset, onCreateTransportRoute, onDispatchTransport, onSetAutomation, onAcceptContract, onChooseSpecialization, onTakeLoan, onSellVehicle, onSetDriverShift, onHireDriver, onRefreshCandidates, onServiceVehicle, onInstallUpgrade, onSetRefuelStrategy, onRefuelVehicle, onClaimGoal, onToggleAccessory }: SectionSheetProps) {
  const allCities = [...customCities, ...cities]
  const [selectedTaxi, setSelectedTaxi] = useState(taxiModels[0].id)
  const [customizingVehicleId, setCustomizingVehicleId] = useState(vehicles[0]?.id ?? '')
  const [fleetView, setFleetView] = useState<'vehicles' | 'market'>('vehicles')
  const [companyView, setCompanyView] = useState<'overview' | 'research'>('overview')
  const [vehiclePanel, setVehiclePanel] = useState<'overview' | 'service' | 'upgrades' | 'style'>('overview')
  const researchCapacity = (hasResearch(completedResearch, 'autonomous-operations') ? 4 : 0) + (hasResearch(completedResearch, 'global-network') ? 4 : 0) + (hasResearch(completedResearch, 'regional-hubs') ? branches.length : 0)
  const fleetCapacity = fleetSlotCapacity(company.level, garageLevel ?? 0, branches) + researchCapacity
  const serviceRadiusKm = maxJobDistanceForFleet(company.level, vehicles.filter((vehicle) => vehicle.type === 'taxi').length) * (hasResearch(completedResearch, 'predictive-demand') ? 1.25 : 1)
  const stationConstructionCost = Math.round(15_000 * (specialization === 'mobility' ? .9 : 1) * (hasResearch(completedResearch, 'prefab-depots') ? .8 : 1))
  const stationVehicle = taxiModels.find((model) => model.id === 'toyota-corolla') ?? taxiModels[0]
  const stationPackageCost = stationConstructionCost + stationVehicle.price
  const fleetFull = vehicles.length >= fleetCapacity
  const nextGarageCost = garageUpgradeCost(garageLevel ?? 0)
  const content = {
    fleet: [`${vehicles.length} vehicle${vehicles.length === 1 ? '' : 's'} in your fleet`, vehicles[0] ? `${vehicles[0].name} · ${vehicles[0].condition}% condition · ${vehicles[0].status}` : 'Purchase your first vehicle.'],
    travel: ['Travel agency locked', 'Reach company level 3 to begin creating tours.'],
    company: ['Your company', 'Manage finances, staff and expansion from here.'],
    finance: ['Financials', 'Track income, expenses and company value.'],
  }[section]
  if (section === 'fleet') {
    const selectedVehicle = vehicles.find((candidate) => candidate.id === customizingVehicleId) ?? vehicles[0]
    const selectedDriver = drivers.find((candidate) => candidate.id === selectedVehicle?.driverId)

    return <section className="section-sheet fleet-sheet game-panel">
    <div className="sheet-handle" /><button className="sheet-close" onClick={onClose} aria-label="Close">×</button>
    <div className="fleet-heading"><div><small>FLEET · {vehicles.length}/{fleetCapacity} SLOTS</small><h2>{vehicles.length} vehicle{vehicles.length === 1 ? '' : 's'}</h2></div><div className="fleet-tabs"><button className={fleetView === 'vehicles' ? 'active' : ''} onClick={() => setFleetView('vehicles')}>My fleet</button><button className={fleetView === 'market' ? 'active' : ''} onClick={() => setFleetView('market')}>＋ Add vehicle</button></div></div>
    {fleetView === 'vehicles' && <>
      <div className="fleet-list">{vehicles.map((vehicle) => { const model = vehicle.type === 'taxi' || vehicle.type === 'rental' ? getModel(vehicle) : undefined; const driver = drivers.find((candidate) => candidate.id === vehicle.driverId); return <button className={`fleet-card ${selectedVehicle?.id === vehicle.id ? 'selected' : ''}`} onClick={() => setCustomizingVehicleId(vehicle.id)} key={vehicle.id}>{model ? <img className="brand-logo" src={model.logoUrl} alt={`${model.brand} logo`} /> : <span className="postal-badge">{vehicle.type === 'coach' ? '🚌' : '📮'}</span>}<div><strong>{vehicle.name}</strong><small>{vehicle.condition}% · {vehicle.rentalJourney ? 'Customer driving' : vehicle.postalRoute ? 'Delivering' : vehicle.scheduledJourney?.kind === 'tour' ? 'Running tour' : vehicle.scheduledJourney?.kind === 'coach' ? 'Intercity service' : vehicle.status === 'on-job' ? 'Driving' : vehicle.serviceTrip ? `To ${vehicle.serviceTrip.label}` : 'Available'}</small><div className="meter-row"><span>⛽ {Math.round(vehicle.fuel)}%</span>{vehicle.type !== 'rental' && <span>😴 {Math.round(driver?.fatigue ?? 0)}%</span>}</div></div></button> })}</div>
      {selectedVehicle && <><div className="vehicle-panel-tabs">{(['overview', 'service', 'upgrades', 'style'] as const).map((panel) => <button className={vehiclePanel === panel ? 'active' : ''} key={panel} onClick={() => setVehiclePanel(panel)}>{panel === 'style' && selectedVehicle.type === 'post' ? 'Route' : panel}</button>)}</div>
        {vehiclePanel === 'overview' && <><div className="vehicle-actions"><div><b>{selectedVehicle.type === 'rental' ? 'Self-drive rental' : selectedDriver?.name ?? '⚠ Driver required'}</b>{selectedDriver && <><small>{selectedDriver.trait ? driverTraitDetails[selectedDriver.trait].label : 'Standard'} · ★ {selectedDriver.rating}</small><button onClick={() => onSetDriverShift(selectedDriver.id, selectedDriver.shift === 'day' ? 'night' : 'day')}>{selectedDriver.shift} shift · change</button></>}</div><button disabled={selectedVehicle.status !== 'available' || vehicles.length <= 1} onClick={() => onSellVehicle(selectedVehicle.id)}>{selectedVehicle.ownership === 'leased' ? 'Return lease' : `Sell · ${money.format(vehicleMarketValue(selectedVehicle))}`}</button></div><VehicleLifecycle vehicle={selectedVehicle} /></>}
        {vehiclePanel === 'service' && <div className="management-card"><b>Maintenance & energy</b><small>{selectedVehicle.condition < 70 ? 'Service recommended' : 'Vehicle is roadworthy'} · costs rise with mileage</small><div className="compact-actions"><button onClick={() => onServiceVehicle(selectedVehicle.id, 'quick')}>Quick +15% · {money.format(maintenanceCost(selectedVehicle, 350))}</button><button onClick={() => onServiceVehicle(selectedVehicle.id, 'full')}>Full +45% · {money.format(maintenanceCost(selectedVehicle, 1_200))}</button><button onClick={() => onServiceVehicle(selectedVehicle.id, 'preventative')}>Major · {money.format(maintenanceCost(selectedVehicle, 2_400))}</button></div><select value={selectedVehicle.refuelStrategy ?? 'automatic'} onChange={(event) => onSetRefuelStrategy(selectedVehicle.id, event.target.value as RefuelStrategy)}><option value="automatic">Automatic recovery</option><option value="fast">Nearby fast · premium price</option><option value="economy">Distant economy · lower price</option><option value="overnight">Overnight depot · cheapest</option></select><button className="mini-primary" disabled={selectedVehicle.fuel >= 100} onClick={() => onRefuelVehicle(selectedVehicle.id)}>Refuel / charge now</button></div>}
        {vehiclePanel === 'upgrades' && <div className="upgrade-grid">{(Object.keys(upgradeDetails) as VehicleUpgrade[]).filter((upgrade) => selectedVehicle.type === 'post' ? upgrade === 'parcel-shelving' || upgrade === 'eco-tires' || upgrade === 'range-pack' : upgrade !== 'parcel-shelving').map((upgrade) => { const info = upgradeDetails[upgrade]; const fitted = (selectedVehicle.upgrades ?? []).includes(upgrade); return <button key={upgrade} disabled={fitted || cash < info.price} onClick={() => onInstallUpgrade(selectedVehicle.id, upgrade)}><strong>{fitted ? '✓ ' : ''}{info.label}</strong><small>{info.description}</small><b>{fitted ? 'Installed' : money.format(info.price)}</b></button> })}</div>}
        {vehiclePanel === 'style' && selectedVehicle.type === 'taxi' && <div className="accessory-grid">{exteriorAccessories.map((accessory) => { const fitted = (selectedVehicle.exteriorAccessories ?? []).includes(accessory.id); return <button className={fitted ? 'fitted' : ''} key={accessory.id} onClick={() => onToggleAccessory(selectedVehicle.id, accessory.id)}><span>{accessory.icon}</span><strong>{accessory.label}</strong><small>{fitted ? 'Fitted · tap to remove' : 'Tap to fit'}</small></button> })}</div>}
        {vehiclePanel === 'style' && selectedVehicle.type === 'post' && <div className="postal-route-control"><small>AUTOMATIC POSTAL ROUND</small><p>Generate a local round and return to the depot automatically.</p><button className="primary-action" disabled={selectedVehicle.status !== 'available'} onClick={() => onStartPostalRoute(selectedVehicle.id)}>{selectedVehicle.postalRoute ? `${selectedVehicle.postalRoute.plannedHours ?? '?'}h route · ${selectedVehicle.postalRoute.stops.length - 2} stops` : 'Generate and start a route'}</button></div>}
      </>}
    </>}
    {fleetView === 'market' && <div className="fleet-market"><div className="garage-card"><span>🏢</span><div><strong>Depot garage · level {garageLevel ?? 0}</strong><small>{vehicles.length}/{fleetCapacity} slots used · each company level adds 2, each garage upgrade adds 3</small></div><button disabled={cash < nextGarageCost} onClick={onUpgradeGarage}>Upgrade · {money.format(nextGarageCost)}</button></div><small className="purchase-label">CHOOSE YOUR NEXT TAXI</small>
    <div className="taxi-shop">{taxiModels.map((model) => <button className={selectedTaxi === model.id ? 'selected' : ''} key={model.id} onClick={() => setSelectedTaxi(model.id)}>
      <img className="brand-logo" src={model.logoUrl} alt={`${model.brand} logo`} loading="lazy" /><strong>{model.brand} {model.name}</strong><small>{model.description}<br />{model.powertrain} · {model.capacity} seats · {model.topSpeedKmh} km/h</small><b>{money.format(model.price)}</b>
    </button>)}</div>
    {(() => { const model = taxiModels.find((taxi) => taxi.id === selectedTaxi) ?? taxiModels[0]; return <div className="purchase-actions"><button className="primary-action" disabled={cash < model.price || fleetFull} onClick={() => onBuyTaxi(model.id)}>{fleetFull ? 'Garage full' : cash < model.price ? 'Not enough cash' : `Buy ${model.name}`}</button><button onClick={() => onLeaseTaxi(model.id)} disabled={company.level < LEASING_UNLOCK_LEVEL || cash < model.price * .1 || fleetFull}>{company.level < LEASING_UNLOCK_LEVEL ? `Lease unlocks at level ${LEASING_UNLOCK_LEVEL}` : fleetFull ? 'Garage full' : `Lease · ${money.format(model.price * .1)} deposit`}</button></div> })()}
    <small className="purchase-label">ADD A POSTAL SERVICE</small>
    <div className="post-shop">{postVehicleModels.map((model) => <div key={model.id}><span>📮</span><div><strong>{model.brand} {model.name}</strong><small>{model.description}<br />{model.powertrain} · {model.capacity} parcels</small></div><b>{money.format(model.price)}</b><button disabled={cash < model.price || fleetFull} onClick={() => onBuyPostVehicle(model.id)}>{fleetFull ? 'Garage full' : 'Buy post van'}</button></div>)}</div>
    <small className="purchase-label">BUILD AN INTERCITY NETWORK</small>
    <div className="feature-card"><span className="feature-icon">🚌</span><div><strong>Empire Intercity Coach</strong><small>48 seats · scheduled city routes · driver required</small></div><b>{money.format(45_000)}</b><button disabled={cash < 45_000 || fleetFull} onClick={onBuyCoach}>{fleetFull ? 'Garage full' : 'Buy coach'}</button></div>
    </div>}
  </section>
  }
  if (section === 'company') return <section className="section-sheet company-sheet game-panel">
    <div className="sheet-handle" /><button className="sheet-close" onClick={onClose} aria-label="Close">×</button><small>COMPANY NETWORK</small><h2>{companyView === 'research' ? 'Innovation lab' : 'Command center'}</h2>
    <div className="company-tabs"><button className={companyView === 'overview' ? 'active' : ''} onClick={() => setCompanyView('overview')}>Operations</button><button className={companyView === 'research' ? 'active' : ''} onClick={() => setCompanyView('research')}>Research <b>{researchPoints(company.level, completedResearch)}</b></button></div>
    {companyView === 'research' ? <ResearchTree company={company} completed={completedResearch} onUnlock={onUnlockResearch} /> : <>
    <div className="finance-summary"><div><small>CASH</small><b>{money.format(cash)}</b></div><div><small>DEBT</small><b>{money.format(loans.reduce((sum, loan) => sum + loan.balance, 0))}</b></div></div>
    <h3>Station network</h3><p>One company manages every station. Each station adds a new service area and arrives with one taxi ready to staff.</p><div className="coverage-summary"><span>◉</span><div><small>RADIUS PER STATION</small><b>{Math.round(serviceRadiusKm)} km · {branches.length} station{branches.length === 1 ? '' : 's'}</b></div></div><button className="place-depot-button" disabled={company.level < 2 || cash < stationPackageCost || fleetFull} onClick={onBuildStation}><span>＋</span><b>{company.level < 2 ? 'Reach level 2 to build again' : 'Build the next station'}</b><small>Station + {stationVehicle.brand} {stationVehicle.name} · {money.format(stationPackageCost)}</small></button><div className="branch-grid">{branches.map((station, index) => <button className={station.cityId === activeCityId ? 'active' : ''} key={station.id} onClick={() => onSwitchStation(station.cityId)}><strong>● {station.name || `Station ${index + 1}`}</strong><small>{station.cityId === activeCityId ? 'Selected · manage upgrades below' : 'View and manage station'}</small></button>)}</div>
    <h3>Selected station</h3>
    {(() => { const branch = branches.find((candidate) => candidate.cityId === activeCityId) ?? branches[0]; return branch && <div className="depot-builder"><div className="depot-heading"><span>🏗️</span><div><strong>{branch.name}</strong><small>Upgrade this station’s capacity and local operations.</small></div></div><div className="depot-grid">{(Object.keys(depotFacilityDetails) as DepotFacility[]).map((facility) => { const details = depotFacilityDetails[facility]; const level = depotFacilityLevel(branch, facility); const cost = depotFacilityUpgradeCost(facility, level); const complete = level >= DEPOT_FACILITY_MAX_LEVEL; return <article key={facility}><span>{details.icon}</span><div><strong>{details.label}</strong><small>{details.description}</small><div className="facility-level" aria-label={`Level ${level} of ${DEPOT_FACILITY_MAX_LEVEL}`}>{[1, 2, 3].map((step) => <i className={step <= level ? 'built' : ''} key={step} />)}</div></div><button disabled={complete || cash < cost} onClick={() => onUpgradeDepotFacility(branch.cityId, facility)}>{complete ? 'MAX' : `Build · ${money.format(cost)}`}</button></article> })}</div></div> })()}
    <h3>Operations manager</h3><div className="management-card"><label className="toggle-row"><span><b>Automatic dispatch</b><small>Accept qualifying calls when a staffed taxi is free.</small></span><input type="checkbox" checked={automation.enabled} onChange={(event) => onSetAutomation({ enabled: event.target.checked })} /></label><label>Minimum fare · {money.format(automation.minFare)}<input type="range" min="0" max="100" step="5" value={automation.minFare} onChange={(event) => onSetAutomation({ minFare: Number(event.target.value) })} /></label></div>
    <h3>Company specialization</h3><div className="specialization-grid">{([['mobility','🚕','Urban Mobility','10% lower expansion costs'],['tourism','🧭','Tourism','20% more tour revenue'],['logistics','📦','Logistics','Postal growth focus'],['sustainability','🌱','Green Fleet','Efficient energy strategy']] as const).map(([id, icon, label, detail]) => <button className={specialization === id ? 'selected' : ''} disabled={Boolean(specialization)} key={id} onClick={() => onChooseSpecialization(id)}><span>{icon}</span><strong>{label}</strong><small>{detail}</small></button>)}</div>
    <h3>Partnership contracts</h3><div className="contract-list">{contracts.map((contract) => <div className={contract.accepted ? 'accepted' : ''} key={contract.id}><span><strong>{contract.name}</strong><small>{contract.description}</small><progress max={contract.target} value={contract.progress} /></span><b>{contract.completed ? 'Reward paid' : `${contract.progress}/${contract.target} · ${money.format(contract.reward)}`}</b>{!contract.accepted && <button onClick={() => onAcceptContract(contract.id)}>Accept</button>}</div>)}</div>
    <h3>Company goals</h3><div className="goal-list">{goals.map((goal) => <div className={goal.completed ? 'complete' : ''} key={goal.id}><small>{goal.cadence.toUpperCase()}</small><strong>{goal.label}</strong><progress max={goal.target} value={goal.progress} /><span>{Math.floor(goal.progress)} / {goal.target} · {money.format(goal.cashReward)} + {goal.reputationReward} rep</span>{goal.completed && !goal.claimed && <button onClick={() => onClaimGoal(goal.id)}>Claim reward</button>}{goal.claimed && <b>✓ Claimed</b>}</div>)}</div>
    <h3>Recruit drivers</h3><p>New vehicles need a hired driver. Salaries and lease costs are paid at the start of each game month.</p><div className="candidate-list">{driverCandidates.map((candidate) => <div key={candidate.id}><strong>{candidate.name} · ★ {candidate.rating}</strong><b>{driverTraitDetails[candidate.trait ?? 'careful'].label}</b><small>{driverTraitDetails[candidate.trait ?? 'careful'].description}</small><span>{money.format(candidate.salary)} / month</span><select defaultValue="" onChange={(event) => event.target.value && onHireDriver(candidate.id, event.target.value)}><option value="">Assign to vehicle…</option>{vehicles.filter((vehicle) => vehicle.type !== 'rental' && !vehicle.driverId).map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.name}</option>)}</select></div>)}</div><button className="refresh-link" onClick={onRefreshCandidates}>Refresh candidates</button>
    {jobs.some((job) => job.status === 'complete' && job.satisfaction != null) && <><h3>Recent passenger feedback</h3><div className="feedback-list">{jobs.filter((job) => job.status === 'complete' && job.satisfaction != null).slice(-3).reverse().map((job) => <div key={job.id}><b>{'★'.repeat(job.customerRating ?? Math.max(1, Math.min(5, Math.ceil((job.satisfaction ?? 0) / 20))))}{'☆'.repeat(5 - (job.customerRating ?? Math.max(1, Math.min(5, Math.ceil((job.satisfaction ?? 0) / 20)))))} · {job.satisfaction}%</b><span>Tip {money.format(job.tip ?? 0)} · +{(job.reputationEarned ?? 0).toFixed(1)} reputation</span></div>)}</div></>}
    <h3>Business loans</h3><p>Loans include 12% interest and are repaid in ten automatic instalments.</p><div className="loan-actions"><button onClick={() => onTakeLoan(10_000)}>Borrow €10,000</button><button onClick={() => onTakeLoan(25_000)}>Borrow €25,000</button></div>
    <div className="loan-list">{loans.map((loan) => <div key={loan.id}><b>{money.format(loan.balance)} remaining</b><small>{money.format(loan.paymentAmount)} next payment</small></div>)}</div>
    <button className="danger-link" onClick={onReset}>Start a new company</button>
    </>}
  </section>
  if (section === 'travel') {
    const rentals = vehicles.filter((vehicle) => vehicle.type === 'rental')
    const model = taxiModels.find((taxi) => taxi.id === selectedTaxi) ?? taxiModels[0]
    return <section className="section-sheet rental-sheet game-panel">
      <div className="sheet-handle" /><button className="sheet-close" onClick={onClose} aria-label="Close">×</button>
      <small>TRAVEL EMPIRE</small><h2>Travel & route network</h2><p>Build guided experiences, scheduled coach links, and a self-drive rental fleet.</p>
      <h3>International expansion</h3><div className="country-grid">{countries.map((country) => { const licensed = countryLicenses.includes(country.code); const cityCount = allCities.filter((city) => city.countryCode === country.code).length; return <button className={licensed ? 'licensed' : ''} key={country.code} disabled={licensed || company.level < 3 || cash < country.licenseCost} onClick={() => onBuyCountryLicense(country.code)}><span>{country.flag}</span><strong>{country.name}</strong><small>{licensed ? `Licensed · ${cityCount} cities` : company.level < 3 ? 'Reach level 3' : `${money.format(country.licenseCost)} license`}</small><b>{licensed ? '✓' : '→'}</b></button> })}</div>
      <h3>Tour buses</h3><div className="feature-card tour-bus-card"><span className="feature-icon">🚌</span><div><strong>City Sightseer</strong><small>32-seat hybrid bus · built for guided city tours · driver required</small></div><b>{money.format(32_000)}</b><button disabled={cash < 32_000 || fleetFull} onClick={onBuyTourBus}>{fleetFull ? 'Garage full' : cash < 32_000 ? 'Not enough cash' : 'Buy tour bus'}</button></div>
      <h3>Travel agency</h3>{agencies.some((agency) => agency.cityId === activeCityId) ? <div className="feature-stack"><div className="feature-card"><span className="feature-icon">🧭</span><div><strong>{agencies.find((agency) => agency.cityId === activeCityId)?.name}</strong><small>Create real-location city experiences</small></div><button onClick={onCreateTour}>＋ Design tour</button></div>{tours.filter((tour) => agencies.find((agency) => agency.id === tour.agencyId)?.cityId === activeCityId).map((tour) => <div className="route-card" key={tour.id}><span><strong>{tour.name}</strong><small>{tour.stops.length} stops · {money.format(tour.price)} per guest</small></span><select defaultValue="" onChange={(event) => event.target.value && onDispatchTour(tour.id, event.target.value)}><option value="">Dispatch tour vehicle…</option>{vehicles.filter((vehicle) => vehicle.cityId === activeCityId && vehicle.status === 'available' && vehicle.driverId && (vehicle.type === 'taxi' || vehicle.type === 'coach')).map((vehicle) => <option value={vehicle.id} key={vehicle.id}>{vehicle.serviceClass === 'tour-bus' ? '🚌 TOUR BUS · ' : ''}{vehicle.name} · {vehicle.capacity} seats</option>)}</select></div>)}</div> : <div className="locked-feature"><b>Open a local travel agency</b><small>{company.level < 3 ? 'Reach company level 3' : `${money.format(5_000)} setup cost`}</small><button disabled={company.level < 3 || cash < 5_000} onClick={onOpenAgency}>Open agency</button></div>}
      <h3>Intercity coach routes</h3><div className="feature-stack"><select defaultValue="" onChange={(event) => event.target.value && onCreateCoachRoute(event.target.value)}><option value="">Create route from {getCity(activeCityId, customCities)?.name}…</option>{allCities.filter((city) => city.id !== activeCityId).map((city) => <option key={city.id} value={city.id}>to {city.name}</option>)}</select>{coachRoutes.filter((route) => route.fromCityId === activeCityId).map((route) => <div className="route-card" key={route.id}><span><strong>🚌 {route.name}</strong><small>{money.format(route.ticketPrice)} ticket · scheduled service</small></span><select defaultValue="" onChange={(event) => event.target.value && onDispatchCoach(route.id, event.target.value)}><option value="">Assign intercity coach…</option>{vehicles.filter((vehicle) => vehicle.type === 'coach' && vehicle.serviceClass !== 'tour-bus' && vehicle.status === 'available' && vehicle.driverId).map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.name}</option>)}</select></div>)}</div>
      <h3>Rail, sea & air</h3><div className="mode-grid">{(Object.keys(transportModels) as TransportMode[]).map((mode) => { const model = transportModels[mode]; const owned = transportAssets.filter((asset) => asset.mode === mode); return <article className="mode-card" key={mode}><header><span>{model.icon}</span><div><strong>{model.label}</strong><small>{model.model} · {model.capacity} passengers</small></div></header><div className="mode-stats"><span>{owned.length} owned</span><span>{model.speedKmh} km/h</span></div><button disabled={company.level < model.unlockLevel || cash < model.price} onClick={() => onBuyTransportAsset(mode)}>{company.level < model.unlockLevel ? `Unlocks level ${model.unlockLevel}` : `Buy · ${money.format(model.price)}`}</button><select defaultValue="" onChange={(event) => event.target.value && onCreateTransportRoute(mode, event.target.value)}><option value="">New {mode === 'airliner' ? 'flight' : mode} route…</option>{allCities.filter((city) => city.id !== activeCityId && countryLicenses.includes(city.countryCode)).map((city) => <option key={city.id} value={city.id}>to {city.name}</option>)}</select></article> })}</div>
      <div className="multimodal-routes">{transportRoutes.filter((route) => route.fromCityId === activeCityId).map((route) => { const model = transportModels[route.mode]; return <div className="route-card" key={route.id}><span className="route-mode">{model.icon}</span><span><strong>{route.name}</strong><small>{model.label} · {money.format(route.ticketPrice)} ticket</small></span><select defaultValue="" onChange={(event) => event.target.value && onDispatchTransport(route.id, event.target.value)}><option value="">Dispatch…</option>{transportAssets.filter((asset) => asset.mode === route.mode && asset.status === 'available' && asset.cityId === route.fromCityId).map((asset) => <option key={asset.id} value={asset.id}>{asset.name}</option>)}</select></div> })}</div>
      {transportAssets.some((asset) => asset.journey) && <div className="active-services"><small>ACTIVE INTERNATIONAL SERVICES</small>{transportAssets.filter((asset) => asset.journey).map((asset) => <div key={asset.id}><span>{transportModels[asset.mode].icon}</span><b>{asset.name}</b><small>to {getCity(asset.journey!.destinationCityId, customCities)?.name} · earns {money.format(asset.journey!.reward)}</small></div>)}</div>}
      <div className="rental-summary"><span><small>AVAILABLE</small><b>{rentals.filter((vehicle) => vehicle.status === 'available').length}</b></span><span><small>ON RENT</small><b>{rentals.filter((vehicle) => vehicle.rentalJourney).length}</b></span></div>
      {rentals.length > 0 && <><h3>Rental fleet</h3><div className="rental-list">{rentals.map((vehicle) => <div key={vehicle.id}><img className="brand-logo" src={getModel(vehicle)?.logoUrl} alt="" /><span><strong>{vehicle.name}</strong><small>{vehicle.rentalJourney ? `Customer driving · earns ${money.format(vehicle.rentalJourney.reward)}` : `${Math.round(vehicle.fuel)}% energy · ${Math.round(vehicle.condition)}% condition`}</small></span><button disabled={vehicle.status !== 'available' || vehicle.fuel < 20 || vehicle.condition < 30} onClick={() => onStartRental(vehicle.id)}>{vehicle.rentalJourney ? 'On rent' : 'Rent out'}</button></div>)}</div></>}
      <h3>Add a rental car</h3><div className="taxi-shop rental-shop">{taxiModels.slice(0, 6).map((candidate) => <button className={selectedTaxi === candidate.id ? 'selected' : ''} key={candidate.id} onClick={() => setSelectedTaxi(candidate.id)}><img className="brand-logo" src={candidate.logoUrl} alt={`${candidate.brand} logo`} /><strong>{candidate.brand} {candidate.name}</strong><small>{candidate.powertrain} · {candidate.capacity} seats</small><b>{money.format(candidate.price)}</b></button>)}</div>
      <button className="primary-action" disabled={cash < model.price || fleetFull} onClick={() => onBuyRentalCar(model.id)}>{fleetFull ? 'Garage full' : cash < model.price ? 'Not enough cash' : `Buy ${model.name} for rentals`}</button>
    </section>
  }
  return <section className="section-sheet game-panel">
    <div className="sheet-handle" /><button className="sheet-close" onClick={onClose} aria-label="Close">×</button>
    <small>{section.toUpperCase()}</small><h2>{content[0]}</h2><p>{content[1]}</p>
  </section>
}
