import { useCurrency } from './CurrencyContext'
import type { BrandStrategy, Competitor, CustomerReview, Difficulty, Dispatcher, DispatcherStrategy, Driver, DriverCertification, Mechanic, Vehicle, VehicleIncident, WorldCondition } from '../../models/game'

const certifications: DriverCertification[] = ['accessible', 'executive', 'coach', 'hazardous']

interface Props {
  cash: number; competitors: Competitor[]; difficulty: Difficulty; condition: WorldCondition; incidents: VehicleIncident[]; brand: BrandStrategy; drivers: Driver[]; vehicles: Vehicle[]
  onDifficulty: (value: Difficulty) => void; onBrand: (patch: Partial<BrandStrategy>) => void; onMarketing: (campaign: BrandStrategy['marketingCampaign']) => void; onPartner: (id: string) => void; onAcquire: (id: string) => void; onTrain: (driverId: string, certification: DriverCertification) => void; onResolve: (id: string) => void
  mechanics: Mechanic[]; dispatchers: Dispatcher[]; reviews: CustomerReview[]; onRecruitMechanic: () => void; onRecruitDispatcher: () => void; onDispatcherStrategy: (id: string, strategy: DispatcherStrategy) => void; onReviewResponse: (id: string, response: 'thanks' | 'apology' | 'voucher' | 'dispute') => void
}

export function WorldManagement({ cash, competitors, difficulty, condition, incidents, brand, drivers, vehicles, mechanics, dispatchers, reviews, onDifficulty, onBrand, onMarketing, onPartner, onAcquire, onTrain, onResolve, onRecruitMechanic, onRecruitDispatcher, onDispatcherStrategy, onReviewResponse }: Props) {
  const { money } = useCurrency()
  return <div className="world-management">
    <div className="condition-hero"><span>{condition.weather === 'rain' ? '🌧️' : condition.weather === 'snow' ? '🌨️' : condition.weather === 'storm' ? '⛈️' : condition.weather === 'heatwave' ? '🌡️' : '☀️'}</span><div><small>LIVE OPERATING CONDITIONS · {condition.temperatureC}°C</small><strong>{condition.weather} · {condition.disruption.replace('-', ' ')}</strong><p>{condition.description}</p></div></div>

    <h3>Competitive market</h3><label className="world-select">AI aggression<select value={difficulty} onChange={(event) => onDifficulty(event.target.value as Difficulty)}><option value="relaxed">Relaxed</option><option value="standard">Standard</option><option value="ruthless">Ruthless</option></select></label>
    <div className="competitor-grid">{competitors.map((competitor) => { const price = Math.round(competitor.cash * .7 + competitor.fleetSize * 6_000); return <article key={competitor.id} style={{ '--rival': competitor.color } as React.CSSProperties}><header><i /><div><strong>{competitor.name}</strong><small>{competitor.relationship} · {competitor.marketShare.toFixed(1)}% market share</small></div></header><div className="rival-stats"><span><b>{competitor.fleetSize}</b> vehicles</span><span><b>{competitor.stationCount}</b> stations</span><span><b>{competitor.serviceQuality}</b> quality</span></div><div className="compact-actions"><button onClick={() => onPartner(competitor.id)}>{competitor.relationship === 'partner' ? 'End partnership' : 'Negotiate partnership'}</button><button disabled={cash < price} onClick={() => onAcquire(competitor.id)}>Acquire · {money.format(price)}</button></div></article> })}</div>

    <h3>Brand, fares & marketing</h3><div className="brand-console"><label>Company color<input type="color" value={brand.primaryColor} onChange={(event) => onBrand({ primaryColor: event.target.value })} /></label><label>Fare position<select value={brand.fareStrategy} onChange={(event) => onBrand({ fareStrategy: event.target.value as BrandStrategy['fareStrategy'] })}><option value="value">Value · −12% fares</option><option value="standard">Standard fares</option><option value="premium">Premium · +22% fares</option></select></label><div className="safety-score"><small>SAFETY RATING</small><b>{brand.safetyRating}%</b></div><div className="campaign-row">{([['local',1000],['digital',2500],['event',5000]] as const).map(([campaign, price]) => <button className={brand.marketingCampaign === campaign ? 'active' : ''} disabled={cash < price} key={campaign} onClick={() => onMarketing(campaign)}>{campaign}<small>{money.format(price)}</small></button>)}</div></div>

    <h3>Roadside incidents</h3><div className="incident-list">{incidents.filter((incident) => !incident.resolved).length === 0 ? <p>✓ No vehicles currently require roadside recovery.</p> : incidents.filter((incident) => !incident.resolved).map((incident) => <article key={incident.id}><span>⚠️</span><div><strong>{incident.kind.toUpperCase()}</strong><small>{incident.description}</small></div><button disabled={cash < incident.repairCost} onClick={() => onResolve(incident.id)}>Recover · {money.format(incident.repairCost)}</button></article>)}</div>

    <h3>Driver academy</h3><div className="academy-list">{drivers.map((driver) => <article key={driver.id}><div><strong>{driver.name} · Level {Math.floor((driver.experience ?? 0) / 100) + 1}</strong><small>{driver.completedTrips ?? 0} trips · {driver.morale ?? 80}% morale · {money.format(driver.careerEarnings ?? 0)} career earnings</small><progress max="100" value={(driver.experience ?? 0) % 100} /></div><div className="certification-row">{certifications.map((certification) => <button disabled={(driver.certifications ?? []).includes(certification) || cash < 1_500} key={certification} onClick={() => onTrain(driver.id, certification)}>{(driver.certifications ?? []).includes(certification) ? '✓ ' : ''}{certification}</button>)}</div><small>Assigned: {vehicles.find((vehicle) => vehicle.driverId === driver.id)?.name ?? 'Unassigned'} · training {money.format(1_500)}</small></article>)}</div>

    <h3>Workshop team</h3><div className="staff-list">{mechanics.map((mechanic) => <article key={mechanic.id}><b>🔧 {mechanic.name}</b><small>{mechanic.specialization} specialist · skill {mechanic.skill} · diagnostics {mechanic.diagnostics} · speed {mechanic.speed}</small><span>{money.format(mechanic.salary)} / month</span></article>)}</div><button className="mini-primary" onClick={onRecruitMechanic}>Recruit mechanic</button>

    <h3>Dispatch team</h3><div className="staff-list">{dispatchers.map((dispatcher) => <article key={dispatcher.id}><b>🎧 {dispatcher.name}</b><small>Capacity {dispatcher.capacity} vehicles · planning {dispatcher.planning} · local knowledge {dispatcher.localKnowledge}</small><select value={dispatcher.strategy} onChange={(event) => onDispatcherStrategy(dispatcher.id, event.target.value as DispatcherStrategy)}>{(['nearest','profit','customer','balanced','territory','contracts'] as DispatcherStrategy[]).map((strategy) => <option value={strategy} key={strategy}>{strategy}</option>)}</select></article>)}</div><button className="mini-primary" onClick={onRecruitDispatcher}>Recruit dispatcher</button>

    <h3>Recent customer reviews</h3><div className="review-list">{reviews.length === 0 ? <p>No customer reviews yet.</p> : [...reviews].reverse().slice(0, 12).map((review) => <article key={review.id}><header><b>{'★'.repeat(review.rating)}{'☆'.repeat(5 - review.rating)}</b><small>{review.headline}</small></header><p>{review.comment}</p><div>{review.positiveTags.map((tag) => <span className="positive" key={tag}>{tag}</span>)}{review.negativeTags.map((tag) => <span className="negative" key={tag}>{tag}</span>)}</div>{review.companyResponse ? <em>Responded: {review.companyResponse}</em> : <nav><button onClick={() => onReviewResponse(review.id, 'thanks')}>Thank</button><button onClick={() => onReviewResponse(review.id, 'apology')}>Apologize</button><button disabled={cash < 100} onClick={() => onReviewResponse(review.id, 'voucher')}>Voucher · {money.format(100)}</button><button onClick={() => onReviewResponse(review.id, 'dispute')}>Dispute</button></nav>}</article>)}</div>
  </div>
}
