import { useState } from 'react'
import { DispatchMap, type Coordinate, type Job, type TripPhase } from './DispatchMap'

type Tab = 'map' | 'jobs' | 'fleet' | 'company'
const places = [
  ['Dame Street','Dublin 2','Dublin Airport T1','Dublin','24.50','12.4','24'],
  ['Grafton Street','Dublin 2','Ballsbridge','Dublin 4','13.80','5.6','14'],
  ["St. Stephen's Green",'Dublin 2','Tallaght','Dublin 24','28.10','15.8','28'],
  ['IFSC','Dublin 1','Blanchardstown Centre','Dublin 15','31.40','18.3','31'],
]
const jobs: Job[] = places.map((p,i)=>({id:String(i),passenger:'Standard',pickupName:p[0],dropoffName:p[2],pickup:[-6.27+i*.01,53.35+i*.006] as Coordinate,dropoff:[-6.24-i*.01,53.39-i*.008] as Coordinate,fare:Number(p[4]),eta:Number(p[6])}))
const paths: Record<string,string>={wallet:'M4 7h16v12H4zM7 4h10v3m0 6h3',star:'m12 3 3 6 6 1-4.5 4 1 7-5.5-3-5.5 3 1-7L3 10l6-1 3-6Z',menu:'M5 7h14M5 12h14M5 17h14',map:'m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Zm6-3v15m6-12v15',jobs:'M8 5V3h8v2M5 5h14v16H5zM9 10h6m-6 5h6',fleet:'M5 16h14l-2-6H7l-2 6Zm2 0v3m10-3v3',company:'M4 21V8l8-4 8 4v13M8 11h2m4 0h2m-8 4h2m4 0h2',target:'M12 3v4m0 10v4M3 12h4m10 0h4m-5 0a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',layers:'m4 9 8-5 8 5-8 5-8-5Zm0 5 8 5 8-5'}
function Icon({name}:{name:string}){return <svg viewBox="0 0 24 24"><path d={paths[name]}/></svg>}

function Header(){return <header className="dashboard"><div className="stat"><span className="stat-icon"><Icon name="wallet"/></span><span><strong>€12,450</strong><small>Balance</small></span></div><div className="stat level"><b className="level-badge">4</b><span className="level-copy"><strong>Level 4</strong><i><b/></i><small>780 / 1200 XP</small></span></div><div className="stat rating"><Icon name="star"/><span><strong>4.6</strong><small>Rating</small></span><Icon name="menu"/></div></header>}
function Nav({tab,setTab}:{tab:Tab,setTab:(t:Tab)=>void}){return <nav className="bottom-nav">{(['map','jobs','fleet','company'] as Tab[]).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}><Icon name={t}/><span>{t[0].toUpperCase()+t.slice(1)}</span></button>)}</nav>}

function Jobs(){return <section className="page"><div className="title-row"><div><h1>Jobs</h1><p>Choose a job to assign to a taxi</p></div><button className="pill">⌯ &nbsp; Filter</button></div><div className="tabs"><b>Available <i>5</i></b><span>Accepted <i>2</i></span><span>Completed <i>18</i></span></div><div className="job-cards">{places.map((p)=><article className="job-card" key={p[0]}><div className="route"><i/><div><label>PICKUP</label><strong>{p[0]}</strong><small>{p[1]}</small></div><i/><div><label>DESTINATION</label><strong>{p[2]}</strong><small>{p[3]}</small></div><footer>♧ {p[5]} km  ◷ {p[6]} min</footer></div><div className="fare"><span>Standard ♟ 1-4</span><strong>€{p[4]}</strong><small>Estimated fare</small><button>Accept</button></div></article>)}</div></section>}
const fleet=[['TAXI-001','Toyota Corolla Hybrid','85%','45,120 km','John Murphy','4.8','In Service'],['TAXI-002','Skoda Octavia','72%','38,760 km','Aoife Walsh','4.7','In Service'],['TAXI-003','Hyundai Ioniq Hybrid','48%','62,310 km','Service Due','in 1 day','Maintenance'],['TAXI-004','Kia Niro EV','90%','22,150 km',"Liam O’Connor",'4.9','In Service'],['TAXI-005','Volkswagen Passat','15%','67,890 km','Not Assigned','','Out of Service'],['TAXI-006','Mercedes Vito','68%','31,540 km','Cian Byrne','4.6','In Service']]
function Fleet(){return <section className="page"><div className="title-row"><div><h1>Fleet</h1><p>Manage your vehicles and drivers</p></div><button className="pill">⌕ ⌯ Filter</button></div><div className="metrics">{[['12','Total Vehicles'],['8','In Service'],['2','Maintenance'],['2','Out of Service']].map(x=><div><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><div className="fleet-list"><header>YOUR VEHICLES <span>12 Vehicles</span></header>{fleet.map((v)=><article><i className={v[6].replaceAll(' ','').toLowerCase()}/><div className="car">🚘</div><div><strong>{v[0]} <em>{v[6]}</em></strong><p>{v[1]}</p><small>▱ {v[2]} | ◉ {v[3]}</small></div><div className="driver"><b>{v[4]}</b><span>{v[5]&&`⭐ ${v[5]}`}</span></div><b>›</b></article>)}<button className="add">＋ Add Vehicle</button></div></section>}
function Company(){return <section className="page"><div className="title-row"><div><h1>Company</h1><p>Overview and management</p></div></div><article className="profile"><span className="stat-icon"><Icon name="company"/></span><div><h2>Travel Empire Ltd.</h2><p>Your taxi company</p><small>⌖ Dublin, Ireland ▣ Founded May 2024</small></div><button className="pill">Edit Profile</button></article><article className="overview"><h2>Company Overview <small>This Week⌄</small></h2><div>{[['128','Total Rides','↑ 12%'],['€3,245','Revenue','↑ 8%'],['24','Active Drivers','↑ 4%'],['4.6','Company Rating','↑ 0.2']].map(x=><span><b>{x[0]}</b><small>{x[1]}</small><em>{x[2]}</em></span>)}</div></article><article className="finance"><h2>Finance <small>This Month⌄</small></h2><p>Revenue</p><b>€12,450</b><em>↑ 15% <small>vs last month</small></em><div className="chart">╱╱╱╲╱╱╱╲╱╱╱╲╱╱●</div></article><article className="management"><h2>Company Management</h2><div>{['👥 Drivers','🚘 Vehicles','🏢 Stations','💼 Services','🏷 Pricing','⚙ Settings'].map(x=><button>{x}<small>Manage {x.split(' ')[1].toLowerCase()}</small></button>)}</div></article></section>}

export default function App(){const [tab,setTab]=useState<Tab>('map');const station:Coordinate=[-6.2763,53.3498];return <main className="app">{tab==='map'&&<><DispatchMap jobs={jobs} selectedJob={null} activeJob={null} phase={'idle' as TripPhase} station={station} placingStation={false} onSelectJob={()=>setTab('jobs')} onStationPlaced={()=>{}} onPhaseChange={()=>{}} onTripComplete={()=>{}}/><div className="map-tools"><button><Icon name="target"/></button><button><Icon name="layers"/></button></div><button className="jobs-fab" onClick={()=>setTab('jobs')}><Icon name="jobs"/> Jobs <b>3</b></button></>}{tab!=='map'&&<div className="screen">{tab==='jobs'?<Jobs/>:tab==='fleet'?<Fleet/>:<Company/>}</div>}<Header/><Nav tab={tab} setTab={setTab}/></main>}
